### ISSUE TITLE
Missing test code for Chapter 9: MonteCarlo Swap

### ISSUE THREAD

**Issue by KennethQNgo** [mdcourse/mdcourse.github.io#18]
I noticed that Chapter 9 of the documentation doesn't include test code, unlike the previous chapters. Would you like me to add a test for the Monte Carlo swap? I have a branch in my repository with test code for the MC swap, and it seems to work, but I'm encountering some issues related to high energy values in the simulation. If this is something we want to include, I'd be happy to contribute the test code.

**Comment by simongravelle** [comment]
Oh yes, if you want, that would be awesome. Currently, the MC swap part is indeed not very well-developed, and there may be some error in the code as well.

On the side note, ideally, the test should be very light, as it will run systematically on the GitHub servers. So if you can keep it shorter than a few tens of seconds, it would be perfect.

**Comment by simongravelle** [comment]
I am closing this issue following PR #20, thank you @KennethQNgo
